const express=require('express');
const router=express.Router();
const bcrypt=require('bcryptjs');
const {getDb}=require('../db/database');

const auth=(req,res,next)=>{if(!req.session.user)return res.status(401).json({error:'No autenticado'});next();};
const admin=(req,res,next)=>{if(!req.session.user||req.session.user.rol!=='admin')return res.status(403).json({error:'Solo admin'});next();};
const sid=(req)=>req.session.user.sucursal_id;
const db=()=>getDb();

router.get('/sucursales',async(req,res)=>{try{const r=await db().query('SELECT * FROM sucursales ORDER BY nombre');res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});

router.post('/sucursales',admin,async(req,res)=>{try{const {nombre,direccion}=req.body;if(!nombre)return res.status(400).json({error:'Nombre requerido'});const r=await db().query('INSERT INTO sucursales (nombre,direccion) VALUES ($1,$2) RETURNING id',[nombre,direccion||'']);const newSid=r.rows[0].id;const hash=bcrypt.hashSync('admin123',10);await db().query('INSERT INTO usuarios (sucursal_id,nombre,usuario,password,rol) VALUES ($1,$2,$3,$4,$5)',[newSid,'Admin '+nombre,'admin_s'+newSid,hash,'admin']);const tarifas=await db().query('SELECT * FROM tarifas WHERE sucursal_id=$1',[sid(req)]);for(const t of tarifas.rows)await db().query('INSERT INTO tarifas (sucursal_id,modalidad_id,modalidad_nombre,horario,vehiculo_id,vehiculo_label,tramo,tramo_label,precio) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[newSid,t.modalidad_id,t.modalidad_nombre,t.horario,t.vehiculo_id,t.vehiculo_label,t.tramo,t.tramo_label,t.precio]);const nueva=await db().query('SELECT * FROM sucursales WHERE id=$1',[newSid]);res.json(nueva.rows[0]);}catch(e){res.status(500).json({error:e.message});}});

router.put('/sucursales/:id',admin,async(req,res)=>{try{await db().query('UPDATE sucursales SET nombre=$1,direccion=$2 WHERE id=$3',[req.body.nombre,req.body.direccion,req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

router.get('/usuarios',auth,async(req,res)=>{try{const r=await db().query('SELECT id,nombre,usuario,rol,turno,cupo,activo FROM usuarios WHERE sucursal_id=$1 ORDER BY nombre',[sid(req)]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});

router.post('/usuarios',admin,async(req,res)=>{try{const {nombre,usuario,password,rol,turno,cupo}=req.body;if(!nombre||!usuario)return res.status(400).json({error:'Datos incompletos'});const ex=await db().query('SELECT id FROM usuarios WHERE usuario=$1',[usuario]);if(ex.rows[0])return res.status(400).json({error:'Usuario ya existe'});const r=await db().query('INSERT INTO usuarios (sucursal_id,nombre,usuario,password,rol,turno,cupo) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id',[sid(req),nombre,usuario,bcrypt.hashSync(password||'enc123',10),rol||'encargado',turno||'',cupo||null]);res.json({id:r.rows[0].id,nombre,usuario,rol,turno,cupo});}catch(e){res.status(500).json({error:e.message});}});

router.put('/usuarios/:id',admin,async(req,res)=>{try{const u=(await db().query('SELECT * FROM usuarios WHERE id=$1 AND sucursal_id=$2',[req.params.id,sid(req)])).rows[0];if(!u)return res.status(404).json({error:'No encontrado'});await db().query('UPDATE usuarios SET nombre=$1,turno=$2,rol=$3,activo=$4,cupo=$5 WHERE id=$6',[req.body.nombre||u.nombre,req.body.turno??u.turno??'',req.body.rol||u.rol,req.body.activo!==undefined?req.body.activo:u.activo,req.body.cupo!==undefined?req.body.cupo||null:u.cupo,u.id]);if(req.body.password)await db().query('UPDATE usuarios SET password=$1 WHERE id=$2',[bcrypt.hashSync(req.body.password,10),u.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

// CUPOS por playa
router.get('/cupos',auth,async(req,res)=>{try{const s=sid(req);const suc=(await db().query('SELECT * FROM sucursales WHERE id=$1',[s])).rows[0];const tots=(await db().query('SELECT modalidad,COUNT(*) as c FROM clientes WHERE sucursal_id=$1 AND activo=1 GROUP BY modalidad',[s])).rows;const cnt={};tots.forEach(r=>{cnt[r.modalidad]=parseInt(r.c);});const turno1=cnt['turno1']||0;const turno2=cnt['turno2']||0;const mensual24=cnt['mensual24']||0;const otros=Object.entries(cnt).filter(([k])=>!['turno1','turno2','mensual24'].includes(k)).reduce((s,[,v])=>s+v,0);const total=turno1+turno2+mensual24+otros;res.json({sucursal:suc,cupo_total:suc.cupo_total,cupo_turno1:suc.cupo_turno1,cupo_turno2:suc.cupo_turno2,cupo_mensual24:suc.cupo_mensual24,ocupado_turno1:turno1,ocupado_turno2:turno2,ocupado_mensual24:mensual24,ocupado_otros:otros,ocupado_total:total});}catch(e){res.status(500).json({error:e.message});}});

router.put('/cupos',auth,async(req,res)=>{try{const{cupo_total,cupo_turno1,cupo_turno2,cupo_mensual24}=req.body;await db().query('UPDATE sucursales SET cupo_total=$1,cupo_turno1=$2,cupo_turno2=$3,cupo_mensual24=$4 WHERE id=$5',[cupo_total||null,cupo_turno1||null,cupo_turno2||null,cupo_mensual24||null,sid(req)]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

router.get('/tarifas',auth,async(req,res)=>{try{const r=await db().query('SELECT * FROM tarifas WHERE sucursal_id=$1 ORDER BY modalidad_id,vehiculo_id,tramo',[sid(req)]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});

router.put('/tarifas',admin,async(req,res)=>{try{for(const u of req.body.updates)await db().query('UPDATE tarifas SET precio=$1 WHERE id=$2 AND sucursal_id=$3',[u.precio,u.id,sid(req)]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

router.get('/clientes',auth,async(req,res)=>{try{const {activo}=req.query;let q='SELECT * FROM clientes WHERE sucursal_id=$1';const p=[sid(req)];if(activo!==undefined){q+=' AND activo=$2';p.push(activo==='true'||activo==='1'?1:0);}const r=await db().query(q+' ORDER BY nombre',p);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});

router.get('/clientes/:id',auth,async(req,res)=>{try{const r=await db().query('SELECT * FROM clientes WHERE id=$1 AND sucursal_id=$2',[req.params.id,sid(req)]);if(!r.rows[0])return res.status(404).json({error:'No encontrado'});res.json(r.rows[0]);}catch(e){res.status(500).json({error:e.message});}});

router.post('/clientes',auth,async(req,res)=>{try{const d=req.body;if(!d.nombre||!d.modalidad)return res.status(400).json({error:'Nombre y modalidad requeridos'});
if(d.turno_encargado_id){const enc=(await db().query('SELECT cupo FROM usuarios WHERE id=$1',[d.turno_encargado_id])).rows[0];if(enc?.cupo){const act=parseInt((await db().query('SELECT COUNT(*) as c FROM clientes WHERE turno_encargado_id=$1 AND activo=1',[d.turno_encargado_id])).rows[0].c);if(act>=enc.cupo)return res.status(409).json({error:'Cupo lleno para este turno'});}}
const r=await db().query(`INSERT INTO clientes (sucursal_id,nombre,dni,cel,tel,tel_ref_parentesco,dom,trabajo,modalidad,turno_encargado_id,vehiculo1_tipo,vehiculo1_marca,vehiculo1_modelo,vehiculo1_color,vehiculo1_patente,vehiculo2_tipo,vehiculo2_marca,vehiculo2_modelo,vehiculo2_color,vehiculo2_patente,obs,ingreso,activo) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,1) RETURNING id`,[sid(req),d.nombre,d.dni||'',d.cel||'',d.tel||'',d.tel_ref_parentesco||'',d.dom||'',d.trabajo||'',d.modalidad,d.turno_encargado_id||null,d.vehiculo1_tipo||'auto',d.vehiculo1_marca||'',d.vehiculo1_modelo||'',d.vehiculo1_color||'',d.vehiculo1_patente||'',d.vehiculo2_tipo||'',d.vehiculo2_marca||'',d.vehiculo2_modelo||'',d.vehiculo2_color||'',d.vehiculo2_patente||'',d.obs||'',d.ingreso||'']);const nuevo=await db().query('SELECT * FROM clientes WHERE id=$1',[r.rows[0].id]);res.json(nuevo.rows[0]);}catch(e){res.status(500).json({error:e.message});}});

router.put('/clientes/:id',auth,async(req,res)=>{try{const d=req.body;const c=(await db().query('SELECT * FROM clientes WHERE id=$1 AND sucursal_id=$2',[req.params.id,sid(req)])).rows[0];if(!c)return res.status(404).json({error:'No encontrado'});await db().query(`UPDATE clientes SET nombre=$1,dni=$2,cel=$3,tel=$4,tel_ref_parentesco=$5,dom=$6,trabajo=$7,modalidad=$8,turno_encargado_id=$9,vehiculo1_tipo=$10,vehiculo1_marca=$11,vehiculo1_modelo=$12,vehiculo1_color=$13,vehiculo1_patente=$14,vehiculo2_tipo=$15,vehiculo2_marca=$16,vehiculo2_modelo=$17,vehiculo2_color=$18,vehiculo2_patente=$19,obs=$20,ingreso=$21 WHERE id=$22 AND sucursal_id=$23`,[d.nombre,d.dni||'',d.cel||'',d.tel||'',d.tel_ref_parentesco||'',d.dom||'',d.trabajo||'',d.modalidad,d.turno_encargado_id||null,d.vehiculo1_tipo||'auto',d.vehiculo1_marca||'',d.vehiculo1_modelo||'',d.vehiculo1_color||'',d.vehiculo1_patente||'',d.vehiculo2_tipo||'',d.vehiculo2_marca||'',d.vehiculo2_modelo||'',d.vehiculo2_color||'',d.vehiculo2_patente||'',d.obs||'',d.ingreso||'',req.params.id,sid(req)]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

router.post('/clientes/:id/baja',admin,async(req,res)=>{try{await db().query('UPDATE clientes SET activo=0,fecha_baja=$1 WHERE id=$2 AND sucursal_id=$3',[req.body.fecha_baja||new Date().toISOString().slice(0,10),req.params.id,sid(req)]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

router.post('/clientes/:id/reactivar',admin,async(req,res)=>{try{await db().query('UPDATE clientes SET activo=1,fecha_baja=NULL WHERE id=$1 AND sucursal_id=$2',[req.params.id,sid(req)]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

router.get('/pagos',auth,async(req,res)=>{try{const {cliente_id,mes,anio}=req.query;let q=`SELECT p.*,c.nombre as cliente_nombre,u.nombre as encargado_nombre FROM pagos p LEFT JOIN clientes c ON c.id=p.cliente_id LEFT JOIN usuarios u ON u.id=p.encargado_id WHERE p.sucursal_id=$1 AND p.anulado=0`;const p=[sid(req)];let i=2;if(cliente_id){q+=` AND p.cliente_id=$${i++}`;p.push(cliente_id);}if(mes){q+=` AND p.mes=$${i++}`;p.push(mes);}if(anio){q+=` AND substring(p.mes,1,4)=$${i++}`;p.push(anio);}const r=await db().query(q+' ORDER BY p.created_at DESC',p);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});

router.post('/pagos',auth,async(req,res)=>{try{const d=req.body;if(!d.cliente_id||!d.fecha||!d.mes)return res.status(400).json({error:'Datos incompletos'});const monto_efectivo=parseFloat(d.monto_efectivo)||0;const monto_transferencia=parseFloat(d.monto_transferencia)||0;const importe_abonado=monto_efectivo+monto_transferencia||parseFloat(d.importe_abonado)||0;const forma_pago=monto_efectivo>0&&monto_transferencia>0?'mixto':monto_transferencia>0?'transferencia':'efectivo';const r=await db().query('INSERT INTO pagos (sucursal_id,cliente_id,fecha,mes,importe_esperado,importe_abonado,monto_efectivo,monto_transferencia,forma_pago,encargado_id,obs) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id',[sid(req),d.cliente_id,d.fecha,d.mes,d.importe_esperado||0,importe_abonado,monto_efectivo,monto_transferencia,forma_pago,req.session.user.id,d.obs||'']);const nuevo=await db().query('SELECT * FROM pagos WHERE id=$1',[r.rows[0].id]);res.json(nuevo.rows[0]);}catch(e){res.status(500).json({error:e.message});}});

router.put('/pagos/:id',admin,async(req,res)=>{try{const p=(await db().query('SELECT * FROM pagos WHERE id=$1 AND sucursal_id=$2',[req.params.id,sid(req)])).rows[0];if(!p)return res.status(404).json({error:'No encontrado'});const me=parseFloat(req.body.monto_efectivo)??p.monto_efectivo??0;const mt=parseFloat(req.body.monto_transferencia)??p.monto_transferencia??0;const abo=me+mt||req.body.importe_abonado||p.importe_abonado;const fp=me>0&&mt>0?'mixto':mt>0?'transferencia':'efectivo';await db().query('UPDATE pagos SET fecha=$1,mes=$2,importe_esperado=$3,importe_abonado=$4,monto_efectivo=$5,monto_transferencia=$6,forma_pago=$7,obs=$8 WHERE id=$9',[req.body.fecha||p.fecha,req.body.mes||p.mes,req.body.importe_esperado||p.importe_esperado,abo,me,mt,fp,(req.body.obs||p.obs||''),p.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

router.post('/pagos/:id/anular',admin,async(req,res)=>{try{const p=(await db().query('SELECT * FROM pagos WHERE id=$1 AND sucursal_id=$2',[req.params.id,sid(req)])).rows[0];if(!p)return res.status(404).json({error:'No encontrado'});await db().query('UPDATE pagos SET anulado=1,anulado_motivo=$1 WHERE id=$2',[req.body.motivo||'',p.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

router.get('/clientes/:id/cuenta',auth,async(req,res)=>{try{const c=(await db().query('SELECT * FROM clientes WHERE id=$1 AND sucursal_id=$2',[req.params.id,sid(req)])).rows[0];if(!c)return res.status(404).json({error:'No encontrado'});const pagos=(await db().query(`SELECT p.*,u.nombre as encargado_nombre FROM pagos p LEFT JOIN usuarios u ON u.id=p.encargado_id WHERE p.cliente_id=$1 AND p.sucursal_id=$2 ORDER BY p.mes DESC,p.created_at DESC`,[req.params.id,sid(req)])).rows;const meses={};for(const p of pagos){if(!meses[p.mes])meses[p.mes]={mes:p.mes,pagos:[],total_esperado:0,total_abonado:0};meses[p.mes].pagos.push(p);if(!p.anulado){meses[p.mes].total_esperado+=parseFloat(p.importe_esperado);meses[p.mes].total_abonado+=parseFloat(p.importe_abonado);}}const saldo_total=pagos.filter(p=>!p.anulado).reduce((s,p)=>s+(parseFloat(p.importe_abonado)-parseFloat(p.importe_esperado)),0);res.json({cliente:c,cuenta:Object.values(meses).sort((a,b)=>b.mes.localeCompare(a.mes)),saldo_total});}catch(e){res.status(500).json({error:e.message});}});

router.get('/dashboard',auth,async(req,res)=>{try{const s=sid(req);const mes=new Date().toISOString().slice(0,7);const hoy=new Date().toISOString().slice(0,10);const activos=parseInt((await db().query('SELECT COUNT(*) as c FROM clientes WHERE sucursal_id=$1 AND activo=1',[s])).rows[0].c);const pagaron=parseInt((await db().query('SELECT COUNT(DISTINCT cliente_id) as c FROM pagos WHERE sucursal_id=$1 AND mes=$2 AND anulado=0',[s,mes])).rows[0].c);const recMes=parseFloat((await db().query('SELECT COALESCE(SUM(importe_abonado),0) as v FROM pagos WHERE sucursal_id=$1 AND mes=$2 AND anulado=0',[s,mes])).rows[0].v)||0;const recHoy=parseFloat((await db().query('SELECT COALESCE(SUM(importe_abonado),0) as v FROM pagos WHERE sucursal_id=$1 AND fecha=$2 AND anulado=0',[s,hoy])).rows[0].v)||0;const recEfectivo=parseFloat((await db().query('SELECT COALESCE(SUM(monto_efectivo),0) as v FROM pagos WHERE sucursal_id=$1 AND mes=$2 AND anulado=0',[s,mes])).rows[0].v)||0;const recTransferencia=parseFloat((await db().query('SELECT COALESCE(SUM(monto_transferencia),0) as v FROM pagos WHERE sucursal_id=$1 AND mes=$2 AND anulado=0',[s,mes])).rows[0].v)||0;const conSaldo=parseInt((await db().query('SELECT COUNT(DISTINCT cliente_id) as c FROM pagos WHERE sucursal_id=$1 AND mes=$2 AND anulado=0 AND importe_abonado<importe_esperado',[s,mes])).rows[0].c);res.json({activos,pagaron,sinPagar:activos-pagaron,recMes,recHoy,recEfectivo,recTransferencia,conSaldo,mes});}catch(e){res.status(500).json({error:e.message});}});

router.get('/resumen',auth,async(req,res)=>{try{const s=sid(req);const anio=req.query.anio||new Date().getFullYear().toString();const clientes=(await db().query('SELECT id,nombre FROM clientes WHERE sucursal_id=$1 AND activo=1 ORDER BY nombre',[s])).rows;const pagos=(await db().query(`SELECT cliente_id,mes,SUM(importe_abonado) as total FROM pagos WHERE sucursal_id=$1 AND substring(mes,1,4)=$2 AND anulado=0 GROUP BY cliente_id,mes`,[s,anio])).rows;res.json({clientes,pagos});}catch(e){res.status(500).json({error:e.message});}});

router.get('/deudores',auth,async(req,res)=>{try{const s=sid(req);const mes=req.query.mes||new Date().toISOString().slice(0,7);const clientes=(await db().query('SELECT * FROM clientes WHERE sucursal_id=$1 AND activo=1',[s])).rows;const pagos=(await db().query('SELECT cliente_id,SUM(importe_abonado) as abonado,SUM(importe_esperado) as esperado FROM pagos WHERE sucursal_id=$1 AND mes=$2 AND anulado=0 GROUP BY cliente_id',[s,mes])).rows;const map={};pagos.forEach(p=>map[p.cliente_id]={abonado:parseFloat(p.abonado),esperado:parseFloat(p.esperado)});const deudores=clientes.map(c=>{const p=map[c.id];if(!p)return{...c,abonado:0,esperado:0,deuda:0,sin_pago:true};const deuda=parseFloat(p.esperado)-parseFloat(p.abonado);return{...c,abonado:p.abonado,esperado:p.esperado,deuda,sin_pago:false};}).filter(c=>c.sin_pago||c.deuda>0).sort((a,b)=>b.deuda-a.deuda);res.json(deudores);}catch(e){res.status(500).json({error:e.message});}});

router.get('/reportes/pagos',auth,async(req,res)=>{try{const s=sid(req);const {desde,hasta}=req.query;const rows=(await db().query(`SELECT substring(p.mes,1,7) as mes, c.modalidad, SUM(p.importe_abonado) as total, COALESCE(SUM(p.monto_efectivo),0) as efectivo, COALESCE(SUM(p.monto_transferencia),0) as transferencia, COUNT(*) as cantidad FROM pagos p JOIN clientes c ON c.id=p.cliente_id WHERE p.sucursal_id=$1 AND p.anulado=0 AND p.mes>=$2 AND p.mes<=$3 GROUP BY substring(p.mes,1,7),c.modalidad ORDER BY mes DESC,modalidad`,[s,desde||'2020-01',hasta||'2099-12'])).rows;res.json(rows);}catch(e){res.status(500).json({error:e.message});}});

router.get('/migrate', async (req, res) => {
  try {
    await db().query(`
      ALTER TABLE sucursales ADD COLUMN IF NOT EXISTS cupo_total INTEGER DEFAULT NULL;
      ALTER TABLE sucursales ADD COLUMN IF NOT EXISTS cupo_turno1 INTEGER DEFAULT NULL;
      ALTER TABLE sucursales ADD COLUMN IF NOT EXISTS cupo_turno2 INTEGER DEFAULT NULL;
      ALTER TABLE sucursales ADD COLUMN IF NOT EXISTS cupo_mensual24 INTEGER DEFAULT NULL;
    `);
    res.json({ ok: true, mensaje: 'Migración ejecutada' });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});
module.exports=router;
